import {
  QWEN3_0_6B_QUANTIZED,
  QWEN3_0_6B,
  QWEN3_1_7B,
  QWEN3_1_7B_QUANTIZED,
  QWEN3_4B,
  QWEN3_4B_QUANTIZED,
  LLAMA3_2_1B,
  LLAMA3_2_1B_QLORA,
  LLAMA3_2_1B_SPINQUANT,
  LLAMA3_2_3B,
  LLAMA3_2_3B_QLORA,
  LLAMA3_2_3B_SPINQUANT,
  HAMMER2_1_0_5B,
  HAMMER2_1_0_5B_QUANTIZED,
  HAMMER2_1_1_5B,
  HAMMER2_1_1_5B_QUANTIZED,
  HAMMER2_1_3B,
  HAMMER2_1_3B_QUANTIZED,
  QWEN2_5_0_5B,
  QWEN2_5_0_5B_QUANTIZED,
  QWEN2_5_1_5B,
  QWEN2_5_1_5B_QUANTIZED,
  QWEN2_5_3B,
  QWEN2_5_3B_QUANTIZED,
  PHI_4_MINI_4B,
  PHI_4_MINI_4B_QUANTIZED,
} from 'react-native-executorch';

export const startingModels = [
  'LLaMA 3.2 - 1B - SpinQuant',
  'Qwen 3 - 0.6B - Quantized',
  'Qwen 3 - 1.7B - Quantized',
];

export const DEFAULT_MODELS = [
  {
    modelName: 'Qwen 3 - 0.6B - Quantized',
    ...QWEN3_0_6B_QUANTIZED,
    parameters: 0.75,
    modelSize: 0.94,
    featured: true,
    thinking: true,
    labels: ['Fast', 'Quantized', 'Reasoning'],
  },
  {
    modelName: 'Qwen 3 - 0.6B',
    ...QWEN3_0_6B,
    parameters: 0.75,
    modelSize: 1.19,
    featured: true,
    thinking: true,
    labels: ['Balanced', 'Reasoning'],
  },
  {
    modelName: 'Qwen 3 - 1.7B',
    ...QWEN3_1_7B,
    parameters: 2.03,
    modelSize: 3.44,
    featured: true,
    thinking: true,
    labels: ['Smart', 'Reasoning'],
  },
  {
    modelName: 'Qwen 3 - 1.7B - Quantized',
    ...QWEN3_1_7B_QUANTIZED,
    parameters: 2.03,
    modelSize: 2.16,
    featured: true,
    thinking: true,
    labels: ['Smart', 'Quantized', 'Reasoning'],
  },
  {
    modelName: 'Qwen 3 - 4B',
    ...QWEN3_4B,
    parameters: 4.02,
    modelSize: 8.05,
    thinking: true,
    labels: ['Smart', 'Reasoning'],
  },
  {
    modelName: 'Qwen 3 - 4B - Quantized',
    ...QWEN3_4B_QUANTIZED,
    parameters: 4.02,
    modelSize: 3.7,
    thinking: true,
    labels: ['Smart', 'Quantized', 'Reasoning'],
  },
  {
    modelName: 'LLaMA 3.2 - 1B',
    ...LLAMA3_2_1B,
    parameters: 1.24,
    modelSize: 2.47,
    featured: true,
    labels: ['Balanced'],
  },
  {
    modelName: 'LLaMA 3.2 - 1B - QLoRa',
    ...LLAMA3_2_1B_QLORA,
    parameters: 1.24,
    modelSize: 1.18,
    featured: true,
    labels: ['Good at coding', 'Quantized'],
  },
  {
    modelName: 'LLaMA 3.2 - 1B - SpinQuant',
    ...LLAMA3_2_1B_SPINQUANT,
    parameters: 1.24,
    modelSize: 1.14,
    featured: true,
    labels: ['Good at coding', 'Fast', 'Great first model', 'Quantized'],
  },
  {
    modelName: 'LLaMA 3.2 - 3B',
    ...LLAMA3_2_3B,
    parameters: 3.21,
    modelSize: 6.43,
    labels: ['Good at coding'],
  },
  {
    modelName: 'LLaMA 3.2 - 3B - QLoRa',
    ...LLAMA3_2_3B_QLORA,
    parameters: 3.21,
    modelSize: 2.65,
    labels: ['Good at coding', 'Quantized'],
  },
  {
    modelName: 'LLaMA 3.2 - 3B - SpinQuant',
    ...LLAMA3_2_3B_SPINQUANT,
    parameters: 3.21,
    modelSize: 2.55,
    labels: ['Good at coding', 'Fast', 'Quantized'],
  },
  {
    modelName: 'Hammer 2.1 - 0.5B',
    ...HAMMER2_1_0_5B,
    parameters: 0.49,
    modelSize: 0.99,
    labels: ['Fast', 'Function calling'],
  },
  {
    modelName: 'Hammer 2.1 - 0.5B - Quantized',
    ...HAMMER2_1_0_5B_QUANTIZED,
    parameters: 0.49,
    modelSize: 0.81,
    labels: ['Fast', 'Function calling', 'Quantized'],
  },
  {
    modelName: 'Hammer 2.1 - 1.5B',
    ...HAMMER2_1_1_5B,
    parameters: 1.54,
    modelSize: 3.09,
    labels: ['Balanced', 'Function calling'],
  },
  {
    modelName: 'Hammer 2.1 - 1.5B - Quantized',
    ...HAMMER2_1_1_5B_QUANTIZED,
    parameters: 1.54,
    modelSize: 1.76,
    labels: ['Balanced', 'Function calling', 'Quantized'],
  },
  {
    modelName: 'Hammer 2.1 - 3B',
    ...HAMMER2_1_3B,
    parameters: 3.09,
    modelSize: 6.17,
    labels: ['Powerful', 'Function calling'],
  },
  {
    modelName: 'Hammer 2.1 - 3B - Quantized',
    ...HAMMER2_1_3B_QUANTIZED,
    parameters: 3.09,
    modelSize: 2.89,
    labels: ['Powerful', 'Function calling', 'Quantized'],
  },
  {
    modelName: 'Qwen 2.5 - 0.5B',
    ...QWEN2_5_0_5B,
    parameters: 0.49,
    modelSize: 0.99,
    labels: ['Fast', 'Small'],
  },
  {
    modelName: 'Qwen 2.5 - 0.5B - Quantized',
    ...QWEN2_5_0_5B_QUANTIZED,
    parameters: 0.49,
    modelSize: 0.81,
    labels: ['Fast', 'Small'],
  },
  {
    modelName: 'Qwen 2.5 - 1.5B',
    ...QWEN2_5_1_5B,
    parameters: 1.54,
    modelSize: 3.09,
    labels: ['Balanced'],
  },
  {
    modelName: 'Qwen 2.5 - 1.5B - Quantized',
    ...QWEN2_5_1_5B_QUANTIZED,
    parameters: 1.54,
    modelSize: 1.76,
    labels: ['Balanced', 'Quantized'],
  },
  {
    modelName: 'Qwen 2.5 - 3B',
    ...QWEN2_5_3B,
    parameters: 3.09,
    modelSize: 6.17,
    labels: ['Powerful'],
  },
  {
    modelName: 'Qwen 2.5 - 3B - Quantized',
    ...QWEN2_5_3B_QUANTIZED,
    parameters: 3.09,
    modelSize: 2.89,
    labels: ['Powerful', 'Quantized'],
  },
  {
    modelName: 'PHI 4 MINI',
    ...PHI_4_MINI_4B,
    parameters: 3.84,
    modelSize: 7.67,
    labels: ['Good at coding', 'Smart'],
  },
  {
    modelName: 'PHI 4 MINI - Quantized',
    ...PHI_4_MINI_4B_QUANTIZED,
    parameters: 3.84,
    modelSize: 4.5,
    labels: ['Good at coding', 'Quantized'],
  },
];
