const createMockPreset = (): (() => void) => jest.fn();

const mockPresets: Record<string, () => void> = {
  afterglow: createMockPreset(),
  aftershock: createMockPreset(),
  alarm: createMockPreset(),
  anvil: createMockPreset(),
  applause: createMockPreset(),
  ascent: createMockPreset(),
  balloonPop: createMockPreset(),
  barrage: createMockPreset(),
  bassDrop: createMockPreset(),
  batter: createMockPreset(),
  bellToll: createMockPreset(),
  blip: createMockPreset(),
  bloom: createMockPreset(),
  bongo: createMockPreset(),
  boulder: createMockPreset(),
  breakingWave: createMockPreset(),
  breath: createMockPreset(),
  breathing: createMockPreset(),
  buildup: createMockPreset(),
  burst: createMockPreset(),
  buzz: createMockPreset(),
  cadence: createMockPreset(),
  cameraShutter: createMockPreset(),
  canter: createMockPreset(),
  cascade: createMockPreset(),
  castanets: createMockPreset(),
  catPaw: createMockPreset(),
  charge: createMockPreset(),
  chime: createMockPreset(),
  chip: createMockPreset(),
  chirp: createMockPreset(),
  clamor: createMockPreset(),
  clasp: createMockPreset(),
  cleave: createMockPreset(),
  coil: createMockPreset(),
  coinDrop: createMockPreset(),
  combinationLock: createMockPreset(),
  crescendo: createMockPreset(),
  dewdrop: createMockPreset(),
  dirge: createMockPreset(),
  dissolve: createMockPreset(),
  dogBark: createMockPreset(),
  drone: createMockPreset(),
  engineRev: createMockPreset(),
  exhale: createMockPreset(),
  explosion: createMockPreset(),
  fadeOut: createMockPreset(),
  fanfare: createMockPreset(),
  feather: createMockPreset(),
  finale: createMockPreset(),
  fingerDrum: createMockPreset(),
  firecracker: createMockPreset(),
  fizz: createMockPreset(),
  flare: createMockPreset(),
  flick: createMockPreset(),
  flinch: createMockPreset(),
  flourish: createMockPreset(),
  flurry: createMockPreset(),
  flush: createMockPreset(),
  gallop: createMockPreset(),
  gavel: createMockPreset(),
  glitch: createMockPreset(),
  guitarStrum: createMockPreset(),
  hail: createMockPreset(),
  hammer: createMockPreset(),
  heartbeat: createMockPreset(),
  herald: createMockPreset(),
  hoofBeat: createMockPreset(),
  ignition: createMockPreset(),
  impact: createMockPreset(),
  jolt: createMockPreset(),
  keyboardMechanical: createMockPreset(),
  keyboardMembrane: createMockPreset(),
  knell: createMockPreset(),
  knock: createMockPreset(),
  lament: createMockPreset(),
  latch: createMockPreset(),
  lighthouse: createMockPreset(),
  lilt: createMockPreset(),
  lock: createMockPreset(),
  lope: createMockPreset(),
  march: createMockPreset(),
  metronome: createMockPreset(),
  murmur: createMockPreset(),
  nudge: createMockPreset(),
  passingCar: createMockPreset(),
  patter: createMockPreset(),
  peal: createMockPreset(),
  peck: createMockPreset(),
  pendulum: createMockPreset(),
  ping: createMockPreset(),
  pip: createMockPreset(),
  piston: createMockPreset(),
  plink: createMockPreset(),
  plummet: createMockPreset(),
  plunk: createMockPreset(),
  poke: createMockPreset(),
  pound: createMockPreset(),
  powerDown: createMockPreset(),
  propel: createMockPreset(),
  pulse: createMockPreset(),
  pummel: createMockPreset(),
  push: createMockPreset(),
  radar: createMockPreset(),
  rain: createMockPreset(),
  ramp: createMockPreset(),
  rap: createMockPreset(),
  ratchet: createMockPreset(),
  rebound: createMockPreset(),
  ripple: createMockPreset(),
  rivet: createMockPreset(),
  rustle: createMockPreset(),
  shockwave: createMockPreset(),
  snap: createMockPreset(),
  sonar: createMockPreset(),
  spark: createMockPreset(),
  spin: createMockPreset(),
  stagger: createMockPreset(),
  stamp: createMockPreset(),
  stampede: createMockPreset(),
  stomp: createMockPreset(),
  stoneSkip: createMockPreset(),
  strike: createMockPreset(),
  summon: createMockPreset(),
  surge: createMockPreset(),
  sway: createMockPreset(),
  sweep: createMockPreset(),
  swell: createMockPreset(),
  syncopate: createMockPreset(),
  throb: createMockPreset(),
  thud: createMockPreset(),
  thump: createMockPreset(),
  thunder: createMockPreset(),
  thunderRoll: createMockPreset(),
  tickTock: createMockPreset(),
  tidalSurge: createMockPreset(),
  tideSwell: createMockPreset(),
  tremor: createMockPreset(),
  trigger: createMockPreset(),
  triumph: createMockPreset(),
  trumpet: createMockPreset(),
  typewriter: createMockPreset(),
  unfurl: createMockPreset(),
  vortex: createMockPreset(),
  wane: createMockPreset(),
  warDrum: createMockPreset(),
  waterfall: createMockPreset(),
  wave: createMockPreset(),
  wisp: createMockPreset(),
  wobble: createMockPreset(),
  woodpecker: createMockPreset(),
  zipper: createMockPreset(),
};

const systemPresets = {
  impactHeavy: createMockPreset(),
  impactLight: createMockPreset(),
  impactMedium: createMockPreset(),
  impactRigid: createMockPreset(),
  impactSoft: createMockPreset(),
  notificationError: createMockPreset(),
  notificationSuccess: createMockPreset(),
  notificationWarning: createMockPreset(),
  selection: createMockPreset(),
  Android: {
    calendarDate: createMockPreset(),
    clockTick: createMockPreset(),
    confirm: createMockPreset(),
    contextClick: createMockPreset(),
    dragCrossing: createMockPreset(),
    dragStart: createMockPreset(),
    edgeRelease: createMockPreset(),
    edgeSqueeze: createMockPreset(),
    effectClick: createMockPreset(),
    effectDoubleClick: createMockPreset(),
    effectHeavyClick: createMockPreset(),
    effectTick: createMockPreset(),
    gestureEnd: createMockPreset(),
    gestureStart: createMockPreset(),
    keyboardPress: createMockPreset(),
    keyboardRelease: createMockPreset(),
    keyboardTap: createMockPreset(),
    longPress: createMockPreset(),
    primitiveClick: createMockPreset(),
    primitiveLowTick: createMockPreset(),
    primitiveQuickFall: createMockPreset(),
    primitiveQuickRise: createMockPreset(),
    primitiveSlowRise: createMockPreset(),
    primitiveSpin: createMockPreset(),
    primitiveThud: createMockPreset(),
    primitiveTick: createMockPreset(),
    release: createMockPreset(),
    scrollItemFocus: createMockPreset(),
    scrollLimit: createMockPreset(),
    scrollTick: createMockPreset(),
    segmentFrequentTick: createMockPreset(),
    segmentTick: createMockPreset(),
    textHandleMove: createMockPreset(),
    toggleOff: createMockPreset(),
    toggleOn: createMockPreset(),
    virtualKey: createMockPreset(),
    virtualKeyRelease: createMockPreset(),
  },
};

export const Presets = {
  ...mockPresets,
  System: systemPresets,
};

export const Settings = {
  enableHaptics: jest.fn(),
  enableSound: jest.fn(),
  enableCache: jest.fn(),
  clearCache: jest.fn(),
  preloadPresets: jest.fn(),
  stopHaptics: jest.fn(),
  shutDownEngine: jest.fn(),
  getHapticsSupportLevel: jest.fn(() => 2),
  forceHapticsSupportLevel: jest.fn(),
  enableImpulseCompositionMode: jest.fn(),
  setRealtimeComposerStrategy: jest.fn(),
};

export const usePatternComposer = jest.fn(() => ({
  play: jest.fn(),
  stop: jest.fn(),
  parse: jest.fn(),
  isParsed: jest.fn(() => true),
}));

export const useRealtimeComposer = jest.fn(() => ({
  set: jest.fn(),
  playDiscrete: jest.fn(),
  stop: jest.fn(),
  isActive: jest.fn(() => false),
}));

export const useAdaptiveHaptics = jest.fn(() => ({
  play: jest.fn(),
}));

export enum HapticSupport {
  NO_SUPPORT = 0,
  LIMITED_SUPPORT = 1,
  STANDARD_SUPPORT = 2,
  ADVANCED_SUPPORT = 3,
}

export enum RealtimeComposerStrategy {
  ENVELOPE = 0,
  PRIMITIVE_TICK = 1,
  PRIMITIVE_COMPLEX = 2,
  ENVELOPE_WITH_DISCRETE_PRIMITIVES = 3,
}
